services:
  events-manager:
    container_name: ${PROJECT_NAME}_data_events
    hostname: events-manager
    restart: always
    image: events_manager_image
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src/.:/src
    logging:
      driver: "json-file"
      options:
        max-size: 50m
        max-file: "2"
    links:
      - clickhouse
    depends_on:
      - clickhouse
  clickhouse:
    image: clickhouse/clickhouse-server:25.3
    container_name: ${PROJECT_NAME}_clickhouse
    env_file:
      - .env
    ports:
      - "${CLICKHOUSE_EXTERNAL_PORT}:8123"
      - "${CLICKHOUSE_PORT_1}:9000"
      - "${CLICKHOUSE_PORT_2}:9009"
    restart: always
    volumes:
      - clickhouse_volume:/var/lib/clickhouse
volumes:
  clickhouse_volume:
    driver: local
